### ISSUE TITLE
Toaster's Rig Volume scaling not relevant to Kemper's

### ISSUE THREAD

**Issue by skoczy** [virango/Toaster#3]
Windows 7 32-bit, Toaster 1.0.74 ALPHA

Rig volume is somehow incorrectly scaled/counted/set. 
When rig volume on Kemper is at noon 0.0dB (blue arrow) but it is almost full in Toaster (orange arrow). 2 Leds (-18dB) in Kemper is 1.30pm (-18dB) in Toaster.
Requesting value from Kemper by using CTRL+R in Toaster works.

![image](https://cloud.githubusercontent.com/assets/16901952/12748935/bd11c378-c9ad-11e5-8361-f0e62e1ecc37.png)

**Comment by skoczy** [comment]
It may something to do with the fact that RIG VOLUME before minus infinity is about -92dB and maxed out is like 12dB, so the middle is -40 dB but in linear manner. But in the middle it is 0.0dB.

**Comment by virango** [comment]
Fixed with https://github.com/virango/Toaster/commit/a9c27aabbfa3f4c29a3bbada47f33babbcced8d6
