### ISSUE TITLE
Stomp/amp/cab editor screen is not activated on Kemper LCD

### ISSUE THREAD

**Issue by skoczy** [virango/Toaster#4]
Windows 7 32-bit, Toaster 1.0.74 Alpha

While long pressing respective button, stomp/amp/cab editor screen is not activated/deactivated on Kemper LCD (it is activated/deactivated on Toaster soft though).

**Comment by virango** [comment]
This is afaik technically not possible. It is also imo unnecessary: You work either on PC or on KPA.
