### ISSUE TITLE
Toaster crashes on os x when kemper tuner is activated

### ISSUE THREAD

**Issue by allenhuish** [virango/Toaster#6]
I didn't save a crash report.

Tuner activated using footswitch

I am running osx 10.11.3

**Comment by virango** [comment]
I think this is a duplicate of #2.

**Comment by virango** [comment]
Definitely duplicate of #2. Fixed. Reason was a bad packaging. There was an outdated libtoasterwidgets.dynlib inside of the pkg file (why?).
